"""initial_schema

Revision ID: b63de593d625
Revises:
Create Date: 2026-07-30 19:38:30.950406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b63de593d625'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_logs', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_activity_logs_created'), table_name='activity_logs')
    op.drop_index(op.f('idx_activity_logs_user'), table_name='activity_logs')
    op.alter_column('applications', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_applications_job_offer'), table_name='applications')
    op.drop_index(op.f('idx_applications_profile'), table_name='applications')
    op.drop_index(op.f('idx_applications_status'), table_name='applications')
    op.alter_column('certifications', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_certifications_profile'), table_name='certifications')
    op.alter_column('company', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_company_name_trgm'), table_name='company', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('cv', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_cv_profile'), table_name='cv')
    op.alter_column('document_type', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('documents', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_documents_profile'), table_name='documents')
    op.drop_index(op.f('idx_documents_type'), table_name='documents')
    op.alter_column('education', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_education_profile'), table_name='education')
    op.alter_column('experience', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_experience_profile'), table_name='experience')
    op.alter_column('favorites', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_favorites_job_offer'), table_name='favorites')
    op.drop_index(op.f('idx_favorites_profile'), table_name='favorites')
    op.alter_column('interview_answers', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_interview_answers_question'), table_name='interview_answers')
    op.alter_column('interview_questions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_interview_questions_session'), table_name='interview_questions')
    op.alter_column('interview_reports', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_interview_reports_session'), table_name='interview_reports')
    op.alter_column('interview_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('interview_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('interview_sessions', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_interview_sessions_job_offer'), table_name='interview_sessions')
    op.drop_index(op.f('idx_interview_sessions_profile'), table_name='interview_sessions')
    op.alter_column('job_alerts', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_job_alerts_active'), table_name='job_alerts')
    op.drop_index(op.f('idx_job_alerts_user'), table_name='job_alerts')
    op.alter_column('job_matches', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_job_matches_job_offer'), table_name='job_matches')
    op.drop_index(op.f('idx_job_matches_profile'), table_name='job_matches')
    op.drop_index(op.f('idx_job_matches_score'), table_name='job_matches')
    op.alter_column('job_offers', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_job_offers_company'), table_name='job_offers')
    op.drop_index(op.f('idx_job_offers_contract'), table_name='job_offers')
    op.drop_index(op.f('idx_job_offers_description_trgm'), table_name='job_offers', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_job_offers_location'), table_name='job_offers')
    op.drop_index(op.f('idx_job_offers_published'), table_name='job_offers')
    op.drop_index(op.f('idx_job_offers_remote'), table_name='job_offers')
    op.drop_index(op.f('idx_job_offers_source'), table_name='job_offers')
    op.drop_index(op.f('idx_job_offers_status'), table_name='job_offers')
    op.drop_index(op.f('idx_job_offers_title_trgm'), table_name='job_offers', postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('job_preferences', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('job_source', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('language', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notifications', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_notifications_read'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_user'), table_name='notifications')
    op.alter_column('profile_languages', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_profile_languages_language'), table_name='profile_languages')
    op.drop_index(op.f('idx_profile_languages_profile'), table_name='profile_languages')
    op.alter_column('profile_skills', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_profile_skills_profile'), table_name='profile_skills')
    op.drop_index(op.f('idx_profile_skills_skill'), table_name='profile_skills')
    op.alter_column('profiles', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_profiles_user'), table_name='profiles')
    op.alter_column('projects', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_projects_profile'), table_name='projects')
    op.alter_column('skill', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_skill_name_trgm'), table_name='skill', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('user_settings', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('user_settings', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_skill_name_trgm'), 'skill', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('skill', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_projects_profile'), 'projects', ['profile_id'], unique=False)
    op.alter_column('projects', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_profiles_user'), 'profiles', ['user_id'], unique=False)
    op.alter_column('profiles', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_profile_skills_skill'), 'profile_skills', ['skill_id'], unique=False)
    op.create_index(op.f('idx_profile_skills_profile'), 'profile_skills', ['profile_id'], unique=False)
    op.alter_column('profile_skills', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_profile_languages_profile'), 'profile_languages', ['profile_id'], unique=False)
    op.create_index(op.f('idx_profile_languages_language'), 'profile_languages', ['language_id'], unique=False)
    op.alter_column('profile_languages', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_notifications_user'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('idx_notifications_read'), 'notifications', ['is_read'], unique=False)
    op.alter_column('notifications', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('language', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('job_source', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('job_preferences', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_job_offers_title_trgm'), 'job_offers', ['title'], unique=False, postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_job_offers_status'), 'job_offers', ['status'], unique=False)
    op.create_index(op.f('idx_job_offers_source'), 'job_offers', ['job_source_id'], unique=False)
    op.create_index(op.f('idx_job_offers_remote'), 'job_offers', ['remote_type'], unique=False)
    op.create_index(op.f('idx_job_offers_published'), 'job_offers', ['published_at'], unique=False)
    op.create_index(op.f('idx_job_offers_location'), 'job_offers', ['location'], unique=False)
    op.create_index(op.f('idx_job_offers_description_trgm'), 'job_offers', ['description'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_job_offers_contract'), 'job_offers', ['contract_type'], unique=False)
    op.create_index(op.f('idx_job_offers_company'), 'job_offers', ['company_id'], unique=False)
    op.alter_column('job_offers', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_job_matches_score'), 'job_matches', [sa.literal_column('compatibility_score DESC')], unique=False)
    op.create_index(op.f('idx_job_matches_profile'), 'job_matches', ['profile_id'], unique=False)
    op.create_index(op.f('idx_job_matches_job_offer'), 'job_matches', ['job_offer_id'], unique=False)
    op.alter_column('job_matches', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_job_alerts_user'), 'job_alerts', ['user_id'], unique=False)
    op.create_index(op.f('idx_job_alerts_active'), 'job_alerts', ['is_active'], unique=False)
    op.alter_column('job_alerts', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_interview_sessions_profile'), 'interview_sessions', ['profile_id'], unique=False)
    op.create_index(op.f('idx_interview_sessions_job_offer'), 'interview_sessions', ['job_offer_id'], unique=False)
    op.alter_column('interview_sessions', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('interview_sessions', 'started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('interview_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_interview_reports_session'), 'interview_reports', ['interview_session_id'], unique=False)
    op.alter_column('interview_reports', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_interview_questions_session'), 'interview_questions', ['interview_session_id'], unique=False)
    op.alter_column('interview_questions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_interview_answers_question'), 'interview_answers', ['interview_question_id'], unique=False)
    op.alter_column('interview_answers', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_favorites_profile'), 'favorites', ['profile_id'], unique=False)
    op.create_index(op.f('idx_favorites_job_offer'), 'favorites', ['job_offer_id'], unique=False)
    op.alter_column('favorites', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_experience_profile'), 'experience', ['profile_id'], unique=False)
    op.alter_column('experience', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_education_profile'), 'education', ['profile_id'], unique=False)
    op.alter_column('education', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_documents_type'), 'documents', ['document_type_id'], unique=False)
    op.create_index(op.f('idx_documents_profile'), 'documents', ['profile_id'], unique=False)
    op.alter_column('documents', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('document_type', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_cv_profile'), 'cv', ['profile_id'], unique=False)
    op.alter_column('cv', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_company_name_trgm'), 'company', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('company', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_certifications_profile'), 'certifications', ['profile_id'], unique=False)
    op.alter_column('certifications', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('idx_applications_profile'), 'applications', ['profile_id'], unique=False)
    op.create_index(op.f('idx_applications_job_offer'), 'applications', ['job_offer_id'], unique=False)
    op.alter_column('applications', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_activity_logs_user'), 'activity_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_activity_logs_created'), 'activity_logs', ['created_at'], unique=False)
    op.alter_column('activity_logs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    # ### end Alembic commands ###
